### ISSUE TITLE
Add packaging instructions into readme 

### ISSUE THREAD

**Issue by nnashwin** [oakes/play-cljc#16]
Hey Oakes,
I am looking to write a game in clojure, and really enjoy your game engine.
However, I'm not sure where to begin to actually package and run a finished product for any project I have.
I'm sure I could figure out how to compile to javascript then integrate inside of electron somehow, but it seems that it would be helpful to include a section in the readme which discusses suggested deployment / packaging options.

**Comment by oakes** [comment]
If you are distributing on the desktop you should build a native version (as an uberjar), using the command in the readme, rather than a web version. You can then create native installers like .exe from your uberjar with [jpackage](https://docs.oracle.com/en/java/javase/14/jpackage/packaging-overview.html#GUID-C1027043-587D-418D-8188-EF8F44A4C06A).

**Comment by nnashwin** [comment]
Awesome.  Thank you.
