### ISSUE TITLE
Game Loop Question

### ISSUE THREAD

**Issue by kovasap** [oakes/play-cljc#7]
When a play-cljc game runs, my understanding is that it uses a creates a `game` map that stores game state, then continually re-creates it with modifications on every iteration of the game loop.  This make a lot of sense to me, and seems to be idiomatic clojure (I am just starting to learn clojure too, so correct me if I'm wrong!).  One thing that confuses me is that in the hello_world game, there is an additional `state` atom in the `core.cljc` file.  This atom seems to also store game state.  Is there a reason why both of these maps exist?  What criteria is used to determine which map stores what data?  Is there a reason why this mutable construct is used here as opposed to something immutable?

**Comment by oakes** [comment]
That's a good question. You can definitely use the `game` map to store things that are only changed within the game loop. But things like `:pressed-keys` need to be in the `*state` atom because it is modified asynchronously by the keyboard event listeners in `start.clj` and `start.cljs`, not from within the game loop. So in short, you can definitely utilize the `game` map for storing most other things, but in the template I think I decided to just put everything specific to your game in `*state` to avoid confusion.

**Comment by kovasap** [comment]
Ok cool, that makes sense.  Thanks!
